spring.application.name=finance_tracker
spring.datasource.username=mario
spring.datasource.password=mario
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker_db
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8081